
name: Build release from master change

on:
   push:
     branches: [ master ]

jobs:
  build:
    name: Maven & Docker Build
    runs-on: ubuntu-latest
    env:
      REPO: docker.pkg.github.com/acerecedoat/prova1/app
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml -Ddocker.skip=true -Ddocker2.registry2=docker.pkg.github.com/acerecedoat/prova1/alm-automation-billing -Ddocker.username=$docker_username -Ddocker.password=$docker_password 
      env:
        docker.username: ${{ secrets.DOCKER_USERNAME }}
        docker.password: ${{ secrets.DOCKER_PASSWORD }}
        docker_username: ${{ secrets.DOCKER_USERNAME }}
        docker_password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} docker.pkg.github.com/acerecedoat/prova1/app
    - name: Build Docker image
      run: docker build -t $REPO:latest -t $REPO:${GITHUB_SHA::8} .
    - name: Publish Docker image
      run: docker push $REPO
      
      
      
