
name: Build Release 

on:
   push:
     branches: [ master ]

jobs:
  build:
    name: Maven & Docker Build
    runs-on: ubuntu-latest
    env:
      REPO: docker.pkg.github.com/ALM-Multicloud-Assets/alm-automation-billing/alm-automation-billing
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml -Ddocker.skip=true
        
    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} $REPO
      
    - name: Build Docker image
      run: docker build -t $REPO:latest -t $REPO:${GITHUB_SHA::8} .
      
    - name: Publish Docker image
      run: docker push $REPO
      
      
      
