# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
#  pull_request:
#    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Build cmd
      run: echo $DICKERUSR 
      env:
        DICKERUSR: ${{ secrets.DOCKER_USERNAME }}
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml -Ddocker.username=$DICKERUSR -Ddocker.password=$DOCKERPWD
      env:
        DICKERUSR: ${{ secrets.DOCKER_USERNAME }}
        DOCKERPWD: ${{ secrets.DOCKER_PASSWORD }}
